version: "3"

services:
  app:
    image: docker-nextjs-dev
    build: .
    restart: always
    volumes:
      - ./components:/app/components
      - ./models:/app/models
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./utils:/app/utils
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db