import bcrypt from 'bcrypt';

const data = {
  areas: [
    {
      name: 'Area 1',
      code: 'A216001',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 2',
      code: 'A216002',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 3',
      code: 'A216003',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 4',
      code: 'A216004',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 5',
      code: 'A216005',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 6',
      code: 'A216006',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 7',
      code: 'A216007',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 8',
      code: 'A216008',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 9',
      code: 'A216009',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 10',
      code: 'A216010',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 11',
      code: 'A216011',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 12',
      code: 'A216012',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 13',
      code: 'A216013',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 14',
      code: 'A216014',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 15',
      code: 'A216015',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 16',
      code: 'A216016',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 17',
      code: 'A216017',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 18',
      code: 'A216018',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 19',
      code: 'A216019',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 20',
      code: 'A216020',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 21',
      code: 'A216021',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 22',
      code: 'A216022',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 23',
      code: 'A216023',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 24',
      code: 'A216024',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 25',
      code: 'A216025',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 26',
      code: 'A216026',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 27',
      code: 'A216027',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 28',
      code: 'A216028',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 29',
      code: 'A216029',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 30',
      code: 'A216030',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 31',
      code: 'A216031',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 32',
      code: 'A216032',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 33',
      code: 'A216033',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 34',
      code: 'A216034',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 35',
      code: 'A216035',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 36',
      code: 'A216036',
      incomeLevel: 'Low',
      localNames: ' Kandikole --  Phwetekere --  Kaondo --  St Johns --  etc.',
    },
    {
      name: 'Area 37',
      code: 'A216037',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 38',
      code: 'A216038',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 39',
      code: 'A216039',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 40',
      code: 'A216040',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 41',
      code: 'A216041',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 42',
      code: 'A216042',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 43',
      code: 'A216043',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 44',
      code: 'A216044',
      incomeLevel: 'Low',
      localNames: ' Kauma --  Nyama --  etc.',
    },
    {
      name: 'Area 45',
      code: 'A216045',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 46',
      code: 'A216046',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 47',
      code: 'A216047',
      incomeLevel: 'High',
      localNames: ' Unknown',
    },
    {
      name: 'Area 48',
      code: 'A216048',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 49',
      code: 'A216049',
      incomeLevel: 'Middle',
      localNames: ' Unknown',
    },
    {
      name: 'Area 50',
      code: 'A216050',
      incomeLevel: 'Low',
      localNames: ' Mgona --  Chatata --  etc.',
    },
    {
      name: 'Area 51',
      code: 'A216051',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 52',
      code: 'A216052',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 53',
      code: 'A216053',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 54',
      code: 'A216054',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 55',
      code: 'A216055',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 56',
      code: 'A216056',
      incomeLevel: 'Low',
      localNames: ' Ntandire --  Mtsiriza --  etc.',
    },
    {
      name: 'Area 57',
      code: 'A216057',
      incomeLevel: 'Low',
      localNames: ' Chinsapo --  etc.',
    },
    {
      name: 'Area 58',
      code: 'A216058',
      incomeLevel: 'Low',
      localNames: ' Unknown',
    },
    {
      name: 'Area 59',
      code: 'A216059',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
    {
      name: 'Area 60',
      code: 'A216060',
      incomeLevel: 'Unknown',
      localNames: ' Unknown',
    },
  ],
  contractors: [
    {
      code: 'C001',
      name: 'Fidelis Building Contractors',
      address: 'Not provided',
      email: 'josephmadaka@gmail.com',
      phone: 'Not provided',
    },
    {
      code: 'C002',
      name: 'DBM Construction',
      address: 'Not provided',
      email: 'dbmconstruction2000@gmail.com',
      phone: 'Not provided',
    },
    {
      code: 'C003',
      name: 'Irrigator System Ltd.',
      address: 'Not provided',
      email: 'irrigatorsystemsltd@gmail.com',
      phone: 'Not provided',
    },
    {
      code: 'C004',
      name: 'Trinkon Group Ltd.',
      address: 'Not provided',
      email: 'info@trinkongroup.com',
      phone: 'Not provided',
    },
  ],
  households: [
    {
      code: 'H00001',
      enrollmentStatus: 'Pending',
      adminNotes: 'Approved',
      blockName: 'Makatani',
      plotNumber: '12/8979',
      email: 'household_test1@test.com',
      headName: 'test name1',
      headNatioalID: 'a2345678',
      phone: '+265 999874512',
      headPhone: '+265 999874512',
      headDateOfBirth: '01-01-1971',
      name: 'Josephy Chimatilo',
      mainSourceOfLiving: 'Begging',
      avarageMonthlyIncomeRange: 'At most MK10 000',
      homeOwnershipStatus: 'Owned',
      structureLocationZone: 'On Land Zoned as residential area',
      currentLatrineType: 'No Latrine',
      isVulnerable: true,
      isPoor: false,
      willPayFullForOSS: true,
    },
    {
      code: 'H00002',
      enrollmentStatus: 'Enrolled',
      adminNotes: 'Problematic household',
      blockName: 'Makatani',
      plotNumber: '12/8980',
      email: 'household_test2@test.com',
      headName: 'test name2',
      headNatioalID: 'a2345679',
      phone: '+265 999874513',
      headPhone: '+265 999874513',
      headDateOfBirth: '01-01-1972',
      name: 'Mary Siliya',
      mainSourceOfLiving: 'Ganyu',
      avarageMonthlyIncomeRange: 'At most MK30 000',
      homeOwnershipStatus: 'Being Purchased',
      structureLocationZone: 'Within a flood-prone area',
      currentLatrineType: 'Flush Toilet',
      isVulnerable: true,
      isPoor: true,
      willPayFullForOSS: false,
    },
    {
      code: 'H00003',
      enrollmentStatus: 'Rejected',
      adminNotes: 'The household is on a very rocky place',
      blockName: 'Makatani',
      plotNumber: '12/8981',
      email: 'household_test3@test.com',
      headName: 'test name3',
      headNatioalID: 'a2345680',
      phone: '+265 999874514',
      headPhone: '+265 999874514',
      headDateOfBirth: '01-01-1973',
      name: 'Enelesi Phiri',
      mainSourceOfLiving: 'Petty Trading',
      avarageMonthlyIncomeRange: 'At most MK50 000',
      homeOwnershipStatus: 'Employer Provided',
      structureLocationZone: 'Within River Buffer',
      currentLatrineType: 'VIP Latrine',
      isVulnerable: false,
      isPoor: true,
      willPayFullForOSS: false,
    },
    {
      code: 'H00004',
      enrollmentStatus: 'Pending',
      adminNotes: 'New application',
      blockName: 'Makatani',
      plotNumber: '12/8982',
      email: 'household_test4@test.com',
      headName: 'test name4',
      headNatioalID: 'a2345681',
      phone: '+265 999874515',
      headPhone: '+265 999874515',
      headDateOfBirth: '01-01-1974',
      name: 'Chikondi Kalizang’oma',
      mainSourceOfLiving: 'Formal Employment',
      avarageMonthlyIncomeRange: 'At most MK100 000',
      homeOwnershipStatus: 'Free and Authorised',
      structureLocationZone: 'On Marginal Land',
      currentLatrineType: 'Latrine with Roof',
      isVulnerable: true,
      isPoor: false,
      willPayFullForOSS: true,
    },
    {
      code: 'H00005',
      enrollmentStatus: 'Enrolled',
      adminNotes: 'The household is unreasonable',
      blockName: 'Makatani',
      plotNumber: '12/8983',
      email: 'household_test5@test.com',
      headName: 'test name5',
      headNatioalID: 'a2345682',
      phone: '+265 999874516',
      headPhone: '+265 999874516',
      headDateOfBirth: '01-01-1975',
      name: 'Andrew Miliwadi',
      mainSourceOfLiving: 'Informal Employment',
      avarageMonthlyIncomeRange: 'Above MK100 000',
      homeOwnershipStatus: 'Free Not Authorised',
      structureLocationZone: 'On Reserved Land/Environmental sensitive',
      currentLatrineType: 'Latrine Without Roof',
      isVulnerable: false,
      isPoor: true,
      willPayFullForOSS: true,
    },
    {
      code: 'H00006',
      enrollmentStatus: 'Rejected',
      adminNotes: 'The household is unreasonable',
      blockName: 'Makatani',
      plotNumber: '12/8984',
      email: 'household_test6@test.com',
      headName: 'test name6',
      headNatioalID: 'a2345683',
      phone: '+265 999874517',
      headPhone: '+265 999874517',
      headDateOfBirth: '01-01-1976',
      name: 'Chimwemwe Chokani',
      mainSourceOfLiving: 'Remittances',
      avarageMonthlyIncomeRange: 'At most MK10 000',
      homeOwnershipStatus: 'Rented',
      structureLocationZone: 'On Land Zoned as residential area',
      currentLatrineType: 'Shared Latrine with neighbors',
      isVulnerable: false,
      isPoor: true,
      willPayFullForOSS: false,
    },
    {
      code: 'H00007',
      enrollmentStatus: 'Pending',
      adminNotes: 'The household is unreasonable',
      blockName: 'Makatani',
      plotNumber: '12/8985',
      email: 'household_test7@test.com',
      headName: 'test name7',
      headNatioalID: 'a2345684',
      phone: '+265 999874518',
      headPhone: '+265 999874518',
      headDateOfBirth: '01-01-1977',
      name: 'Samson Akhalepo',
      mainSourceOfLiving: 'Pension',
      avarageMonthlyIncomeRange: 'At most MK30 000',
      homeOwnershipStatus: 'Owned',
      structureLocationZone: 'Within a flood-prone area',
      currentLatrineType: 'No Latrine',
      isVulnerable: true,
      isPoor: false,
      willPayFullForOSS: true,
    },
    {
      code: 'H00008',
      enrollmentStatus: 'Enrolled',
      adminNotes: 'The household is unreasonable',
      blockName: 'Makatani',
      plotNumber: '12/8986',
      email: 'household_test8@test.com',
      headName: 'test name8',
      headNatioalID: 'a2345685',
      phone: '+265 999874519',
      headPhone: '+265 999874519',
      headDateOfBirth: '01-01-1978',
      name: 'Laston Kufeyani',
      mainSourceOfLiving: 'Subsistence Farming',
      avarageMonthlyIncomeRange: 'At most MK50 000',
      homeOwnershipStatus: 'Being Purchased',
      structureLocationZone: 'Within River Buffer',
      currentLatrineType: 'Flush Toilet',
      isVulnerable: true,
      isPoor: true,
      willPayFullForOSS: false,
    },
  ],
  products: [
    {
      slug: 'pour-flash',
      name: 'Pour Flash',
      description: 'Pour Flash',
      price: 250000,
      image: '/images/pour-flash-1.png',
      secondImage: '/images/pour-flash-2.png',
      maximumQuantityAllowedPerOrder: 3,
      rating: 0,
      numReviews: 0,
      category: 'Waste Management',
    },
    {
      slug: 'tingle-vip',
      name: 'Single VIP',
      description: 'Single VIP',
      price: 150000,
      image: '/images/single-vip-1.png',
      secondImage: '/images/single-vip-2.png',
      maximumQuantityAllowedPerOrder: 3,
      rating: 0,
      numReviews: 0,
      category: 'Waste Management',
    },
    {
      slug: 'twin-vip',
      name: 'Twin VIP',
      description: 'Twin VIP',
      price: 2000000,
      image: '/images/twin-vip-1.png',
      secondImage: '/images/twin-vip-2.png',
      maximumQuantityAllowedPerOrder: 3,
      rating: 0,
      numReviews: 0,
      category: 'Waste Management',
    },
  ],
  users: [
    {
      firstName: 'LCC',
      lastName: 'Admininstrator',
      email: 'admin@lcc.mw',
      password: bcrypt.hashSync('12345678', 12),
      roles: [
        'Household head',
        'Contractor',
        'Ward development',
        'Committee member',
        'Field supervisor',
        'Enumerator',
        'Monitoring and evaluation officer',
        'Systems administrator',
        'Super systems administrator',
      ],
    },
    {
      firstName: 'LWB',
      lastName: 'Admininstrator',
      email: 'admin@lwb.mw',
      password: bcrypt.hashSync('12345678', 12),
      roles: ['Super systems administrator'],
    },
  ],
  wards: [
    {
      code: 'LCC001',
      name: 'Chisapo I ward',
    },
    {
      code: 'LCC002',
      name: 'Chisapo II ward',
    },
    {
      code: 'LCC003',
      name: 'Phwetekere ward',
    },
    {
      code: 'LCC004',
      name: 'Mbidzi ward',
    },
    {
      code: 'LCC005',
      name: 'Chigoneka ward',
    },
    {
      code: 'LCC006',
      name: 'Mtsiliza ward',
    },
    {
      code: 'LCC007',
      name: 'Mvunguti ward',
    },
    {
      code: 'LCC008',
      name: 'Mgona Chatata ward',
    },
    {
      code: 'LCC009',
      name: 'Kabwabwa ward',
    },
    {
      code: 'LCC010',
      name: 'Chimutu ward',
    },
    {
      code: 'LCC011',
      name: 'Nyama ward',
    },
    {
      code: 'LCC012',
      name: 'Mteza ward',
    },
    {
      code: 'LCC013',
      name: 'Milindi ward',
    },
    {
      code: 'LCC014',
      name: 'Nankhaka ward',
    },
    {
      code: 'LCC015',
      name: 'StateHouse ward',
    },
    {
      code: 'LCC016',
      name: 'Chilinde I ward',
    },
    {
      code: 'LCC017',
      name: 'Chilinde II ward',
    },
    {
      code: 'LCC018',
      name: 'Kaliyeka ward',
    },
    {
      code: 'LCC019',
      name: 'Tsabango I Ward',
    },
    {
      code: 'LCC020',
      name: 'Kawale I Ward',
    },
    {
      code: 'LCC021',
      name: 'Kawale II Ward',
    },
    {
      code: 'LCC022',
      name: 'Ngwenya Ward',
    },
    {
      code: 'LCC023',
      name: 'Biwi Ward',
    },
    {
      code: 'LCC024',
      name: 'Mchesi Ward',
    },
    {
      code: 'LCC025',
      name: 'Mtandire Ward',
    },
    {
      code: 'LCC026',
      name: 'Lumbadzi Ward',
    },
    {
      code: 'LCC027',
      name: 'Mariya Ward',
    },
    {
      code: 'LCC028',
      name: 'Sese Ward',
    },
    {
      code: 'LCC029',
      name: 'Tsabango II ward',
    },
  ],
};

export default data;
